import './globals.css';
import { ReduxProvider } from '@/redux/provider';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className="bg-slate-900">
				<main>
					<ReduxProvider>{children}</ReduxProvider>
				</main>
			</body>
		</html>
	);
}
